apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc  # Nombre del PVC
  namespace: redis-server  # Namespace (opcional, si no se especifica usa "default")
spec:
  accessModes:
    - ReadWriteOnce  # Modo de acceso (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  resources:
    requests:
      storage: 1Gi  # Tamaño del almacenamiento
  storageClassName: local-path  # StorageClass (depende de tu cluster)
  volumeMode: Filesystem  # Tipo de volumen (Filesystem o Block)