apiVersion: v1
kind: Service
metadata:
  name: users-api-go-service
spec:
  type: NodePort
  selector:
    app: users-api-go
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
