apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api-go
  template:
    metadata:
      labels:
        app: users-api-go
    spec:
      containers:
      - name: users-api-go
        image: hug58/users-api-go:v1.0.13
        command: ["/users-api"]
        ports:
        - containerPort: 8080
        env:
        - name: PGHOST
          value: "postgres"
        - name: PGDATABASE
          value: postgres
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          value: postgres
        - name: SECRET
          value: SUPERSECRET!
        - name: TOKEN_EXPIRATION_MINUTES
          value: 5m

        - name: REDIS_HOST
          value: "redis-service.redis-server.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "Thomas2025"