name: CI/CD Pipeline

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write  # Permiso esencial para poder hacer push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/users-api-go:v1.0.${{ github.run_number }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/users-api-go:v1.0.${{ github.run_number }}

  update-k8s-and-argocd:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN || github.token }}
          fetch-depth: 0  # Necesario para hacer push

      - name: Update Kubernetes manifests with new image
        run: |
          # Usando sed para actualizar el deployment.yaml
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/users-api-go:v1.0.${{ github.run_number }}|" ./k8s/deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./k8s/deployment.yaml
          git commit -m "Update image to ${{ github.run_number }}"
          git push https://${{ secrets.GH_TOKEN || github.token }}@github.com/${{ github.repository }}.git

      - name: Sync ArgoCD
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            "${{ secrets.ARGOCD_SERVER }}/api/v1/applications/users-api-go/sync"